package com.mmdc.milestone2;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

public class DetailDisplayGUI extends javax.swing.JFrame {
    String employeeID;
    String employeeDetailsCSV;
    EmployeeDatabase db;
    /** Creates new form DetailDisplay */
    public DetailDisplayGUI(String employeeID, String employeeDetailsCSV) {
        initComponents();
        setLocationRelativeTo(null);
        btnAdminConsole.setVisible(false);
        btnManagerConsole.setVisible(false);
        
        this.employeeID = employeeID;
        this.employeeDetailsCSV = employeeDetailsCSV;
        db = new EmployeeDatabase(employeeDetailsCSV);
        setEmployeeDetails();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lblFullName = new javax.swing.JLabel();
        lblEmployeeID = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taAddress = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblPosition = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblSSSNumber = new javax.swing.JLabel();
        lblPhilhealthNumber = new javax.swing.JLabel();
        lblTIN = new javax.swing.JLabel();
        lblBirthday = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnAdminConsole = new javax.swing.JButton();
        btnManagerConsole = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        lblPagIbigNumber = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 600));

        lblFullName.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblFullName.setText("Sabin Miguel Cacho");

        lblEmployeeID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEmployeeID.setText("10001");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Employee ID:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Phone Number:");

        lblPhoneNumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPhoneNumber.setText("09985103116");

        jScrollPane1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        taAddress.setEditable(false);
        taAddress.setColumns(20);
        taAddress.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        taAddress.setLineWrap(true);
        taAddress.setRows(5);
        taAddress.setText("1 Saint Anthony Street, Multinational Village, Paranaque City");
        taAddress.setWrapStyleWord(true);
        jScrollPane1.setViewportView(taAddress);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("SSS Number:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("PhilHealth Number:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("TIN:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Status:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Position:");

        lblPosition.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPosition.setText("Employee");

        lblStatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblStatus.setText("Probation");

        lblSSSNumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSSSNumber.setText("<number>");

        lblPhilhealthNumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPhilhealthNumber.setText("<number>");

        lblTIN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTIN.setText("<number>");

        lblBirthday.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblBirthday.setText("January 31, 2002");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Birthday:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Address:");

        btnAdminConsole.setText("View Admin Console");

        btnManagerConsole.setText("View Manager Console");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Pag-Ibig:");

        lblPagIbigNumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPagIbigNumber.setText("<number>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPhilhealthNumber))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPhoneNumber))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblEmployeeID))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSSSNumber))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblStatus))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPosition))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTIN)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(305, 305, 305)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblBirthday)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(btnAdminConsole, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(btnManagerConsole, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(18, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPagIbigNumber))
                            .addComponent(lblFullName))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFullName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(lblPosition))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(lblStatus))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblEmployeeID))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblPhoneNumber))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lblSSSNumber))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lblPhilhealthNumber)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBirthday)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdminConsole, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnManagerConsole, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(lblPagIbigNumber))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lblTIN))))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailDisplayGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailDisplayGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailDisplayGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailDisplayGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DetailDisplayGUI().setVisible(true);
//            }
//        });
    }
    
    private void setEmployeeDetails(){
        try{
            String line;
            String[] data;
            BufferedReader reader = new BufferedReader(new FileReader(employeeDetailsCSV));
            
            while((line = reader.readLine()) != null){
                data = line.split(",(?=(?:[^\"]*\"[^\"]*\")*[^\"]*$)"); //regex to ignore commas within quotation marks (source: Bart Kiers, https://stackoverflow.com/questions/1757065/java-splitting-a-comma-separated-string-but-ignoring-commas-in-quotes
                   
                if (data[0].equals(employeeID)){
                    
                    data[4] = data[4].replaceAll("\"", ""); //remove quotation marks from values
                    data[13] = data[13].replaceAll("\"", "");
                    data[15] = data[15].replaceAll("\"", "");
                    data[16] = data[16].replaceAll("\"", "");
                    data[17] = data[17].replaceAll("\"", "");
                    data[18] = data[18].replaceAll("\"", "");

                    data[13] = data[13].replaceAll(",", ""); //remove commas from values that will be parsed as doubles
                    data[15] = data[15].replaceAll(",", "");
                    data[16] = data[16].replaceAll(",", "");
                    data[17] = data[17].replaceAll(",", "");
                    data[18] = data[18].replaceAll(",", "");


                    String myString = "";
                    for(String val : data)
                    {
                      myString += (": " + val + "\n");
                    }
                    System.out.println(myString);
                    
                    switch(getPosition(data[11])){ //initialize employee based on position & set relevant button visibility
                        case "Admin":
                            Administrator admin = new Administrator(data[0], data[2], data[1], data[3], data[4], data[5], data[6], data[7], data[8], data[9], data[10], data[11], Double.parseDouble(data[13]), Double.parseDouble(data[15]) + Double.parseDouble(data[16]), Double.parseDouble(data[17]), Double.parseDouble(data[18]));
                            setDetails(data);
                            break;
                        case "Manager":
                            Manager manager = new Manager(data[0], data[2], data[1], data[3], data[4], data[5], data[6], data[7], data[8], data[9], data[10], data[11], Double.parseDouble(data[13]), Double.parseDouble(data[15]) + Double.parseDouble(data[16]), Double.parseDouble(data[17]), Double.parseDouble(data[18]));
                            setDetails(data);
                            break;
                        default:
                            Employee employee = new Employee(data[0], data[2], data[1], data[3], data[4], data[5], data[6], data[7], data[8], data[9], data[10], data[11], Double.parseDouble(data[13]), Double.parseDouble(data[15]) + Double.parseDouble(data[16]), Double.parseDouble(data[17]), Double.parseDouble(data[18]));
                            setDetails(data);
                            break;
                    }
                }
            }
        }
        catch (IOException e){
            System.out.println("Error: " + e.getLocalizedMessage());
        }
    }
    
    private String getPosition(String position){
        if(position.contains("Chief Executive Officer") || position == "Chief Operating Officer" || position == "Chief Finance Officer" || position == "Chief Marketing Officer" || position.contains("Manager")){
            btnManagerConsole.setVisible(true);
            return "Manager";
        }
        else if(position == "IT Operations and Systems" || position.contains("Administrator")){
            btnAdminConsole.setVisible(true);
            return "Admin";
        }
        else return "Employee";
    }
    
    private void setDetails(String[] data){
        lblFullName.setText(data[2] + " " + data[1]);
        lblPosition.setText(data[11]);
        lblBirthday.setText(data[3]);
        lblStatus.setText(data[10]);
        lblEmployeeID.setText(data[0]);
        lblPhoneNumber.setText(data[5]);
        lblSSSNumber.setText(data[6]);
        lblPhilhealthNumber.setText(data[7]);
        lblPagIbigNumber.setText(data[9]);
        lblTIN.setText(data[8]);
        taAddress.setText(data[4]);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminConsole;
    private javax.swing.JButton btnManagerConsole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBirthday;
    private javax.swing.JLabel lblEmployeeID;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblPagIbigNumber;
    private javax.swing.JLabel lblPhilhealthNumber;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblPosition;
    private javax.swing.JLabel lblSSSNumber;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTIN;
    private javax.swing.JTextArea taAddress;
    // End of variables declaration//GEN-END:variables

}
