package com.mmdc.milestone2;

import java.time.Duration;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class ViewPayrollGUI extends javax.swing.JFrame {
    private String lateByTime = "08:11";
    private String attendanceLogPath = "..\\Cacho_Milestone2\\src\\resources\\attendance_logs.csv";
    private Employee employee;
    private ArrayList<String[]> attendanceLog;
    private String[] columnNames = {"ID", "Last Name", "First Name", "Date", "Time In", "Time Out"};
    private EmployeeDatabase db = new EmployeeDatabase();
    private DefaultTableModel tableModel;
    private DateTimeFormatter formatter;
    private PayrollCalculator calculator;
    private long hoursWorked;
    private double grossMonthlySalary;
    private double netMonthlySalary;
    private double sssContribution;
    private double philHealthContribution;
    private double pagIbigContribution;
    private double withholdingTaxDeduction;
    
    /** Creates new form ViewPayrollGUI */
    public ViewPayrollGUI(Employee employee) {
        attendanceLog = db.getAttendanceFromFile(employee.getEmployeeID(), attendanceLogPath); //populate list of attendance log entries
        tableModel = new DefaultTableModel(attendanceLog.toArray(new Object[][]{}), columnNames); //populate table with attendance log list by using a constructed DefaultTableModel
        initComponents();
        setLocationRelativeTo(null);
        
        this.employee = employee;
        setDetailLabels();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane = new javax.swing.JScrollPane();
        tblEntries = new javax.swing.JTable();
        lblFullName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblBasicSalary = new javax.swing.JLabel();
        lblRiceSubsidy = new javax.swing.JLabel();
        lblPhoneAllowance = new javax.swing.JLabel();
        lblClothingAllowance = new javax.swing.JLabel();
        lblGrossSemiMonthlyRate = new javax.swing.JLabel();
        lblHourlyRate = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblHoursWorked = new javax.swing.JLabel();
        lblGrossMonthlySalary = new javax.swing.JLabel();
        lblNetMonthlySalary = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        lblSssContribution = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblPhilHealthContribution = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblPagIbigContribution = new javax.swing.JLabel();
        lblWithholdingTax = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblEntries.setAutoCreateRowSorter(true);
        tblEntries.setModel(tableModel);
        jScrollPane.setViewportView(tblEntries);

        lblFullName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblFullName.setText("<full name>");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Basic Salary:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Rice Subsidy:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Phone Allowance:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Clothing Allowance:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Gross Semi-Monthly Rate:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Hourly Rate:");

        lblBasicSalary.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblBasicSalary.setText("<amount>");

        lblRiceSubsidy.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblRiceSubsidy.setText("<amount>");

        lblPhoneAllowance.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPhoneAllowance.setText("<amount>");

        lblClothingAllowance.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblClothingAllowance.setText("<amount>");

        lblGrossSemiMonthlyRate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblGrossSemiMonthlyRate.setText("<amount>");

        lblHourlyRate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblHourlyRate.setText("<amount>");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Hours Worked:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Gross Monthly Salary:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Net Monthly Salary:");

        lblHoursWorked.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblHoursWorked.setText("<amount>");

        lblGrossMonthlySalary.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblGrossMonthlySalary.setText("<amount>");

        lblNetMonthlySalary.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNetMonthlySalary.setText("<amount>");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("SSS Contribution:");

        lblSssContribution.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSssContribution.setText("<amount>");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setText("PhilHealth Contribution:");

        lblPhilHealthContribution.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPhilHealthContribution.setText("<amount>");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setText("Pag-Ibig Contribution");

        lblPagIbigContribution.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPagIbigContribution.setText("<amount>");

        lblWithholdingTax.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblWithholdingTax.setText("<amount>");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setText("Withholding Tax:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBasicSalary)
                            .addComponent(lblRiceSubsidy)
                            .addComponent(lblClothingAllowance)
                            .addComponent(lblGrossSemiMonthlyRate)
                            .addComponent(lblHourlyRate)
                            .addComponent(lblPhoneAllowance)))
                    .addComponent(lblFullName))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNetMonthlySalary)
                    .addComponent(lblGrossMonthlySalary)
                    .addComponent(lblHoursWorked)
                    .addComponent(lblSssContribution)
                    .addComponent(lblPhilHealthContribution)
                    .addComponent(lblPagIbigContribution)
                    .addComponent(lblWithholdingTax))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFullName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(lblBasicSalary))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblRiceSubsidy)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblPhoneAllowance)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblClothingAllowance)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblGrossSemiMonthlyRate)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblHourlyRate)))
                                .addGap(166, 166, 166))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                                .addGap(23, 23, 23))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(lblHoursWorked))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(lblGrossMonthlySalary))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(lblSssContribution))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(lblPhilHealthContribution))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(lblPagIbigContribution))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(lblWithholdingTax))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(lblNetMonthlySalary))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPayrollGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPayrollGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPayrollGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPayrollGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ViewPayrollGUI().setVisible(true);
//            }
//        });
    }
    
    private void setDetailLabels(){
        lblFullName.setText(employee.getLastName() + ", " + employee.getFirstName());
        lblBasicSalary.setText(Double.toString(employee.getBasicSalary()).format("%.2f"));
        lblRiceSubsidy.setText(Double.toString(employee.getRiceSubsidy()).format("%.2f"));
        lblPhoneAllowance.setText(Double.toString(employee.getPhoneAllowance()).format("%.2f"));
        lblClothingAllowance.setText(Double.toString(employee.getClothingAllowance()).format("%.2f"));
        lblGrossSemiMonthlyRate.setText(Double.toString(employee.getGrossSalary()).format("%.2f"));
        lblHourlyRate.setText(Double.toString(employee.getHourlyRate()).format("%.2f"));
        
        calculatePayrollDetails();
        lblHoursWorked.setText(Long.toString(hoursWorked).format("%.2f"));
        lblGrossMonthlySalary.setText(Double.toString(grossMonthlySalary).format("%.2f"));
        lblSssContribution.setText(Double.toString(sssContribution).format("%.2f"));
        lblPhilHealthContribution.setText(Double.toString(philHealthContribution).format("%.2f"));
        lblPagIbigContribution.setText(Double.toString(pagIbigContribution).format("%.2f"));
        lblWithholdingTax.setText(Double.toString(withholdingTaxDeduction).format("%.2f"));
        lblNetMonthlySalary.setText(Double.toString(netMonthlySalary).format("%.2f"));
    }
    
    private void calculatePayrollDetails(){
        Double[] payrollDetails = new Double[6];
        PayrollCalculator calculator;
        Duration hoursLate = Duration.ZERO; //number of hours late after 8:10
        Duration timeFromCutoff;
        String[] logItem;
        
        for(int i = attendanceLog.size() - 1; i >= attendanceLog.size() - 20; i--){ //iterate through the last 20 attendance logs
            logItem = attendanceLog.get(i);
            if (logItem[4].length() < 5) logItem[4] = "0" + logItem[4]; //make sure that 'Time In' string is always in HH:MM format for parsing;
            timeFromCutoff = Duration.between(LocalTime.parse(logItem[4]), LocalTime.parse(lateByTime)); //gets the length of time between 'Time In' and lateByTime
            if(timeFromCutoff.compareTo(Duration.ZERO) < 0){
                hoursLate = hoursLate.plus(timeFromCutoff);
            }
        }
        hoursWorked = 160 + hoursLate.toHours();
        grossMonthlySalary = (employee.getHourlyRate() * 160) + (employee.getHourlyRate() * hoursLate.toHours());
        calculator = new PayrollCalculator(grossMonthlySalary);
        sssContribution = calculator.calculateSssContribution();
        philHealthContribution = calculator.calculatePhilHealthContribution();
        pagIbigContribution = calculator.calculatePagIbigContribution();
        withholdingTaxDeduction = calculator.calculateWithholdingTax();
        netMonthlySalary = calculator.calculateNetMonthlySalary();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblBasicSalary;
    private javax.swing.JLabel lblClothingAllowance;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblGrossMonthlySalary;
    private javax.swing.JLabel lblGrossSemiMonthlyRate;
    private javax.swing.JLabel lblHourlyRate;
    private javax.swing.JLabel lblHoursWorked;
    private javax.swing.JLabel lblNetMonthlySalary;
    private javax.swing.JLabel lblPagIbigContribution;
    private javax.swing.JLabel lblPhilHealthContribution;
    private javax.swing.JLabel lblPhoneAllowance;
    private javax.swing.JLabel lblRiceSubsidy;
    private javax.swing.JLabel lblSssContribution;
    private javax.swing.JLabel lblWithholdingTax;
    private javax.swing.JTable tblEntries;
    // End of variables declaration//GEN-END:variables

}
